### ISSUE TITLE
Zombie training prototype changes for August 2023 testing

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-sandbox#99]
We are planning to conduct a new round of usability testing (based on issues found in previous testing) for the following components:

- date range picker
- combobox
- input mask
- character count
- tooltip
- validation
- accordion
- file input (new!)

We need to make some changes to some of the component functionality based on what improvements we aim to test in this next round. Some components have no changes to test as we need to gather more data on them first.

**Components that need updates (based on recent improvements we've made) in the prototype:**
- combobox (better navigation using keystrokes and tab/spacebar)
- input mask (include recent improvements from [#5227](https://github.com/uswds/uswds/pull/5227))
- character count (delayed audio feedback, consider adding hint text above the field for screen magnifier users)
- add file input (add most updated version to "Step 1 of 4: Training Details" page)

Everything else stays the same. 

**Changes needed in the [prototype](https://federalist-d5e7c07c-6ffa-4b8e-935f-49a7df24a505.sites.pages.cloud.gov/preview/uswds/uswds-sandbox/jb-zombie-defense-training/) are documented in this [component testing planning mural board](https://app.mural.co/invitation/mural/gsa6/1682975695042?sender=u83d0e400125d69b595f75755&key=4265205b-4557-4ce8-99fe-219d854729c2).** Go to the "Prototype: Zombie defense Training Session" section. Changes are documented with yellow sticky notes.

**Comment by mahoneycm** [comment]
@jaclinec I have a question about the combobox update and just wanted to make sure I understand.

The mural board note sounds like we want to add the keyboard navigation changes previously made to combobox in https://github.com/uswds/uswds/pull/5160 to the _select_ component

![image](https://github.com/uswds/uswds-sandbox/assets/25211650/9c51dab6-ac0b-4fdb-ac5c-1a1a32ceb878)

Happy to take this work on since I did the combobox update!

**Comment by jaclinec** [comment]
Good catch @mahoneycm . I thought that was a combobox but if its a select, I'll need to go back in and figure out how we will test combobox.

**Comment by amyleadem** [comment]
@jaclinec I do not think the changes to input mask will be ready by the end of this sprint. There is a fairly large amount of intricate work still to be done and I don't think we will be able to get to it in time. Let us know if this work needs to be prioritized and we can discuss.

**Comment by jaclinec** [comment]
@mahoneycm I updated the prototype annotation to show where we will add a combobox. We are going to add it in the "Step 1 of 4" screen. The user will select "in-person testing" bubble and then we will show more inputs so they can enter their location, including a combobox for them to enter their state.

**Comment by jaclinec** [comment]
@amyleadem No problem - we can test input mask as-is. We're still at least a couple of weeks away from testing so I will check in again later to see if changes could be ready for testing, but we won't worry about it if not.
